// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type User struct {
	ID         string
	ScreenName string
	UserName   string
	Bio        string
	IsPrivate  bool
	CreatedAt  time.Time
}
