// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"
)

const findUserByID = `-- name: FindUserByID :one
select id from user
where id = ? limit 1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	err := row.Scan(&id)
	return id, err
}
