version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "kyu08"

  # uv が生成する uv.lock を更新するため、pip ecosystem を利用する.
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "kyu08"
