# see: https://golangci-lint.run/usage/configuration/
run:
  concurrency: 4
  timeout: 10m
  go: 1.22

linters:
  # see: https://zenn.dev/sanpo_shiho/books/61bc1e1a30bf27/viewer/642fe9
  enable-all: true
  disable:
    # deprecated
    - deadcode
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - rowserrcheck
    - scopelint
    - structcheck
    - sqlclosecheck
    - varcheck
    - wastedassign
    - execinquery
    - gomnd
    - depguard

    # deprecatedではないが思想が合わないので無効化しているlinterたち
    - varnamelen # 過度に感じたので無効化
    - godox # PRを跨いでTODOコメントを消化することがあるので無効化
    - godot # Comment should end in a period (godot)と怒られるが、日本語とは合わないので無効化
    - wsl # 意味の単位ごとで改行を入れた方が読みやすいケースがあるため無効化
    - testpackage # テスト用のパッケージを切らない方が自由に少ない記述量でテストが書けて嬉しいので無効化

linters-settings:
  revive:
    rules:
      # ライブラリではないのでPublic関数のコメントチェックを無効化
      - name: exported
        disabled: true

  tagliatelle:
    case:
      rules:
        json: snake
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - err113 # テスト時はその場でエラーを作成して比較したりしたいので無効化
