// Code generated by yo. DO NOT EDIT.
// Package dao contains the types.
package dao

import (
	"context"
	"fmt"
	"time"

	"cloud.google.com/go/spanner"
	"google.golang.org/api/iterator"
	"google.golang.org/grpc/codes"
)

// Tweet represents a row from 'Tweet'.
type Tweet struct {
	ID        string    `spanner:"ID" json:"ID"`               // ID
	AuthorID  string    `spanner:"AuthorID" json:"AuthorID"`   // AuthorID
	Body      string    `spanner:"Body" json:"Body"`           // Body
	CreatedAt time.Time `spanner:"CreatedAt" json:"CreatedAt"` // CreatedAt
	UpdatedAt time.Time `spanner:"UpdatedAt" json:"UpdatedAt"` // UpdatedAt
}

func TweetPrimaryKeys() []string {
	return []string{
		"ID",
	}
}

func TweetColumns() []string {
	return []string{
		"ID",
		"AuthorID",
		"Body",
		"CreatedAt",
		"UpdatedAt",
	}
}

func TweetWritableColumns() []string {
	return []string{
		"ID",
		"AuthorID",
		"Body",
		"CreatedAt",
		"UpdatedAt",
	}
}

func (t *Tweet) columnsToPtrs(cols []string, customPtrs map[string]interface{}) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		if val, ok := customPtrs[col]; ok {
			ret = append(ret, val)
			continue
		}

		switch col {
		case "ID":
			ret = append(ret, &t.ID)
		case "AuthorID":
			ret = append(ret, &t.AuthorID)
		case "Body":
			ret = append(ret, &t.Body)
		case "CreatedAt":
			ret = append(ret, &t.CreatedAt)
		case "UpdatedAt":
			ret = append(ret, &t.UpdatedAt)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}
	return ret, nil
}

func (t *Tweet) columnsToValues(cols []string) ([]interface{}, error) {
	ret := make([]interface{}, 0, len(cols))
	for _, col := range cols {
		switch col {
		case "ID":
			ret = append(ret, t.ID)
		case "AuthorID":
			ret = append(ret, t.AuthorID)
		case "Body":
			ret = append(ret, t.Body)
		case "CreatedAt":
			ret = append(ret, t.CreatedAt)
		case "UpdatedAt":
			ret = append(ret, t.UpdatedAt)
		default:
			return nil, fmt.Errorf("unknown column: %s", col)
		}
	}

	return ret, nil
}

// newTweet_Decoder returns a decoder which reads a row from *spanner.Row
// into Tweet. The decoder is not goroutine-safe. Don't use it concurrently.
func newTweet_Decoder(cols []string) func(*spanner.Row) (*Tweet, error) {
	customPtrs := map[string]interface{}{}

	return func(row *spanner.Row) (*Tweet, error) {
		var t Tweet
		ptrs, err := t.columnsToPtrs(cols, customPtrs)
		if err != nil {
			return nil, err
		}

		if err := row.Columns(ptrs...); err != nil {
			return nil, err
		}

		return &t, nil
	}
}

// Insert returns a Mutation to insert a row into a table. If the row already
// exists, the write or transaction fails.
func (t *Tweet) Insert(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TweetWritableColumns())
	return spanner.Insert("Tweet", TweetWritableColumns(), values)
}

// Update returns a Mutation to update a row in a table. If the row does not
// already exist, the write or transaction fails.
func (t *Tweet) Update(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TweetWritableColumns())
	return spanner.Update("Tweet", TweetWritableColumns(), values)
}

// InsertOrUpdate returns a Mutation to insert a row into a table. If the row
// already exists, it updates it instead. Any column values not explicitly
// written are preserved.
func (t *Tweet) InsertOrUpdate(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TweetWritableColumns())
	return spanner.InsertOrUpdate("Tweet", TweetWritableColumns(), values)
}

// UpdateColumns returns a Mutation to update specified columns of a row in a table.
func (t *Tweet) UpdateColumns(ctx context.Context, cols ...string) (*spanner.Mutation, error) {
	// add primary keys to columns to update by primary keys
	colsWithPKeys := append(cols, TweetPrimaryKeys()...)

	values, err := t.columnsToValues(colsWithPKeys)
	if err != nil {
		return nil, newErrorWithCode(codes.InvalidArgument, "Tweet.UpdateColumns", "Tweet", err)
	}

	return spanner.Update("Tweet", colsWithPKeys, values), nil
}

// FindTweet gets a Tweet by primary key
func FindTweet(ctx context.Context, db YORODB, id string) (*Tweet, error) {
	key := spanner.Key{id}
	row, err := db.ReadRow(ctx, "Tweet", key, TweetColumns())
	if err != nil {
		return nil, newError("FindTweet", "Tweet", err)
	}

	decoder := newTweet_Decoder(TweetColumns())
	t, err := decoder(row)
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "FindTweet", "Tweet", err)
	}

	return t, nil
}

// ReadTweet retrieves multiples rows from Tweet by KeySet as a slice.
func ReadTweet(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Tweet, error) {
	var res []*Tweet

	decoder := newTweet_Decoder(TweetColumns())

	rows := db.Read(ctx, "Tweet", keys, TweetColumns())
	err := rows.Do(func(row *spanner.Row) error {
		t, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, t)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadTweet", "Tweet", err)
	}

	return res, nil
}

// Delete deletes the Tweet from the database.
func (t *Tweet) Delete(ctx context.Context) *spanner.Mutation {
	values, _ := t.columnsToValues(TweetPrimaryKeys())
	return spanner.Delete("Tweet", spanner.Key(values))
}

// FindTweetsByAuthorID retrieves multiple rows from 'Tweet' as a slice of Tweet.
//
// Generated from index 'TweetByAuthorID'.
func FindTweetsByAuthorID(ctx context.Context, db YORODB, authorID string) ([]*Tweet, error) {
	const sqlstr = "SELECT " +
		"ID, AuthorID, Body, CreatedAt, UpdatedAt " +
		"FROM Tweet@{FORCE_INDEX=TweetByAuthorID} " +
		"WHERE AuthorID = @param0"

	stmt := spanner.NewStatement(sqlstr)
	stmt.Params["param0"] = authorID

	decoder := newTweet_Decoder(TweetColumns())

	// run query
	YOLog(ctx, sqlstr, authorID)
	iter := db.Query(ctx, stmt)
	defer iter.Stop()

	// load results
	res := []*Tweet{}
	for {
		row, err := iter.Next()
		if err != nil {
			if err == iterator.Done {
				break
			}
			return nil, newError("FindTweetsByAuthorID", "Tweet", err)
		}

		t, err := decoder(row)
		if err != nil {
			return nil, newErrorWithCode(codes.Internal, "FindTweetsByAuthorID", "Tweet", err)
		}

		res = append(res, t)
	}

	return res, nil
}

// ReadTweetsByAuthorID retrieves multiples rows from 'Tweet' by KeySet as a slice.
//
// This does not retrieve all columns of 'Tweet' because an index has only columns
// used for primary key, index key and storing columns. If you need more columns, add storing
// columns or Read by primary key or Query with join.
//
// Generated from unique index 'TweetByAuthorID'.
func ReadTweetsByAuthorID(ctx context.Context, db YORODB, keys spanner.KeySet) ([]*Tweet, error) {
	var res []*Tweet
	columns := []string{
		"ID",
		"AuthorID",
	}

	decoder := newTweet_Decoder(columns)

	rows := db.ReadUsingIndex(ctx, "Tweet", "TweetByAuthorID", keys, columns)
	err := rows.Do(func(row *spanner.Row) error {
		t, err := decoder(row)
		if err != nil {
			return err
		}
		res = append(res, t)

		return nil
	})
	if err != nil {
		return nil, newErrorWithCode(codes.Internal, "ReadTweetsByAuthorID", "Tweet", err)
	}

	return res, nil
}
