CREATE TABLE User (
  ID STRING(36) NOT NULL,
  ScreenName STRING(20) NOT NULL,
  UserName STRING(20) NOT NULL,
  Bio STRING(160) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL
) PRIMARY KEY (ID);

CREATE UNIQUE INDEX UserByScreenName ON User (ScreenName);

CREATE TABLE Tweet (
  ID STRING(36) NOT NULL,
  AuthorID STRING(36) NOT NULL,
  Body STRING(140) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL,
  UpdatedAt TIMESTAMP NOT NULL
) PRIMARY KEY (ID);

CREATE INDEX TweetByAuthorID ON Tweet (AuthorID);
