CREATE TABLE User (
  ID STRING(36) NOT NULL,
  ScreenName STRING(20) NOT NULL,
  UserName STRING(20) NOT NULL,
  Bio STRING(160) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL
) PRIMARY KEY (ID);

CREATE UNIQUE INDEX UserByScreenName ON User (ScreenName);
