name: Lint sql

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.sql'
      - '.sqlfluff'
      - '.github/workflows/lint-sql.yaml'

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
            python-version: "3.12.4"
      - name: Install SQLFluff
        run: pip install sqlfluff==3.1.0
      - name: Lint sql
        run: make lint-sql
